### ISSUE TITLE
Contribute a web framework to display your articles on the web

### ISSUE THREAD

**Issue by ireneontheway** [ireneontheway/ireneontheway.github.io#1]
Hi Francis: @francis-du
I've imported all the files from the [Technical_Communication](https://github.com/ireneontheway/Technical_Communication) repo into this new repo.
Thanks for your previous contribution. Feel free to leave your commits.

**Comment by francis-du** [comment]
Ok i will resubmit

**Comment by francis-du** [comment]
Done
