### ISSUE TITLE
Need to fix the check failures.

### ISSUE THREAD

**Issue by ireneontheway** [ireneontheway/ireneontheway.github.io#3]
To make the structure clearer and fix some picture display problems, I have changed the names of images, files, and folders. 
Can you help me to fix the check failure?
See the link of [my latest update](https://github.com/ireneontheway/ireneontheway.github.io/commit/04bf6d8252b609110fec57572a67c9a2f5e763b0).

**Comment by francis-du** [comment]
Sure

**Comment by francis-du** [comment]
Done
